In [1]:
import matplotlib.pyplot as plt
import numpy as np
from spa.core import spa
from spa.properties import ThresholdProperty
import pandas as pd

In [15]:
data = pd.read_csv('../data/counts.csv')
correct_list = data['is_correct'].values
# Split into 16 lists
split_list = np.split(correct_list, len(correct_list)/16)
split_list

[array([ True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True, False,  True,  True,  True,  True]),
 array([False, False,  True, False, False,  True,  True, False,  True,
        False,  True, False,  True,  True, False, False]),
 array([ True,  True,  True, False,  True, False,  True, False,  True,
         True,  True, False, False, False,  True, False]),
 array([False,  True,  True,  True, False,  True, False,  True, False,
        False, False, False,  True, False,  True, False]),
 array([ True,  True, False, False, False,  True,  True, False, False,
         True,  True, False, False, False, False, False]),
 array([False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False]),
 array([False,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True, False]),
 array([False, False,  True, False,  True, False,  True, False,  True,
         True, Fals

In [16]:
probabilities = []
for byte_list in split_list:
    num_samples = 0
    num_correct_after = 0
    for i, is_correct in enumerate(byte_list):
        if not is_correct or i == 15:
            continue
        num_samples += 1
        if byte_list[i + 1]:
            num_correct_after += 1
        probabilities.append(num_correct_after / num_samples)

print(probabilities)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8571428571428571, 0.875, 0.8888888888888888, 0.8, 0.8181818181818182, 0.8333333333333334, 0.8461538461538461, 0.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.3333333333333333, 0.2857142857142857, 1.0, 1.0, 0.6666666666666666, 0.5, 0.4, 0.5, 0.5714285714285714, 0.5, 0.4444444444444444, 1.0, 1.0, 0.6666666666666666, 0.5, 0.4, 0.3333333333333333, 0.2857142857142857, 1.0, 0.5, 0.6666666666666666, 0.5, 0.6, 0.5, 0.0, 1.0, 0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.7777777777777778, 0.8, 0.8181818181818182, 0.75, 0.0, 0.0, 0.0, 0.25, 0.2, 0.3333333333333333, 0.42857142857142855, 0.375, 1.0, 0.5, 0.6666666666666666, 0.75, 0.6, 0.5, 0.5714285714285714, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.8571428571428571, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.